name: Auto-Create PR from Master to Develop

on:
  workflow_dispatch:

  
jobs:
  backport:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Configure Git
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
      
    - name: Fetch all branches and tags
      run: git fetch --all --tags
      
    - name: Check commit diff between master and develop
      id: commit_diff
      run: |
        DIFF=$(git rev-list --count origin/master..origin/develop)
        echo "Commit difference: $DIFF"
        echo "::set-output name=diff::$DIFF"
      
    - name: Create PR if master is ahead
      if: steps.commit_diff.outputs.diff > 0
      run: |
        TOKEN="${{ secrets.GITHUB_TOKEN }}"
        TITLE="Backport commits from master to develop"
        BODY="This PR is an automated backport from master to develop due to forward commits in master."
        HEAD="master"
        BASE="develop"
        
        PR_URL=$(curl -X POST \
          -H "Authorization: token $TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls \
          -d "{\"title\":\"$TITLE\",\"body\":\"$BODY\",\"head\":\"$HEAD\",\"base\":\"$BASE\"}" \
          | jq -r .html_url)
        
        echo "Created PR: $PR_URL"