name: Git Flow PR Check

on:
  pull_request:
    branches:
      - master
      - develop
      - feature/*
      - hotfix/*
      - release/*

jobs:
  git-flow-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Git
      run: sudo apt-get install git -y

    - name: Check git flow
      run: |
        SOURCE_BRANCH=$(jq -r ".pull_request.head.ref" "$GITHUB_EVENT_PATH")
        TARGET_BRANCH=$(jq -r ".pull_request.base.ref" "$GITHUB_EVENT_PATH")

        if [[ "$SOURCE_BRANCH" == "develop" && "$TARGET_BRANCH" != "release"* ]]; then
          echo "Error: PR from develop can only be merged to release branches."
          #exit 1
        fi

        echo $SOURCE_BRANCH
        echo $TARGET_BRANCH

        if [[ "$SOURCE_BRANCH" != "hotfix"* && "$SOURCE_BRANCH" != "release"* ]]; then
          echo "Error: PR can only be merged from hotfix or release branches."
          #exit 1
        fi