name: Git Flow PR Check

on:
  pull_request:

jobs:
  git-flow-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Git
      run: sudo apt-get install git -y

    - name: Verify branch name
      run: |
        BRANCH_NAME=$(jq --raw-output .pull_request.head.ref "$GITHUB_EVENT_PATH")

        echo "asdfadsfasd"

        echo $BRANCH_NAME
        if [[ "$BRANCH_NAME" =~ ^(master|develop|feature/.*|hotfix/.*|release/.*)$ ]]; then
            BRANCH_NAME_TARGET=$(jq --raw-output .pull_request.base.ref "$GITHUB_EVENT_PATH")
            if [[ "$BRANCH_NAME_TARGET" =~ ^(master|develop|feature/.*|hotfix/.*|release/.*)$ ]]; then
              echo "sdfgsdfgsfdg"
              echo $BRANCH_NAME_TARGET
              echo "Branch name is valid."
            else
              echo "qwewqe"
              echo $BRANCH_NAME_TARGET
              echo "Invalid TARGET branch name. Allowed patterns: master, develop, feature/*, hotfix/*, release/*"
              exit 1
            fi
        else
          echo "Invalid SOURCE branch name. Allowed patterns: master, develop, feature/*, hotfix/*, release/*"
          exit 1
        fi

    - name: Check git flow
      run: |
        SOURCE_BRANCH=$(jq --raw-output .pull_request.head.ref "$GITHUB_EVENT_PATH")
        TARGET_BRANCH=$(jq --raw-output .pull_request.base.ref "$GITHUB_EVENT_PATH")

        echo $SOURCE_BRANCH
        echo $TARGET_BRANCH

        if [[ "$SOURCE_BRANCH" == feature/* && "$TARGET_BRANCH" != "develop" ]]; then
          echo "Source branch is 'feature' and target branch does not start with 'release'."
          exit 1
        fi

        if [[ "$SOURCE_BRANCH" == "develop" && "$TARGET_BRANCH" != release/* ]]; then
          echo "Source branch is 'develop' and target branch does not start with 'release'."
          exit 1
        fi

        if [[ "$SOURCE_BRANCH" == hotfix/* && "$TARGET_BRANCH" != "master" ]]; then
          echo "Source branch is 'hotfix' and target branch does not start with 'master'."
          exit 1
        fi

        if [[ "$SOURCE_BRANCH" == release/* && "$TARGET_BRANCH" != "master" ]]; then
          echo "Source branch is 'release' and target branch does not start with 'master'."
          exit 1
        fi


        if [[ "$SOURCE_BRANCH" == "master" && "$TARGET_BRANCH" != "develop" ]]; then
          echo "Source branch is 'release' and target branch does not start with 'master'."
          exit 1
        fi


        echo "PR valid"

        exit 0
